name: Nate Woods
markdown: redcarpet
highlighter: pygments
permalink: /blog/:year/:month/:title.html
exclude: 
    - node_modules
    - gruntfile.js
    - package.json
    - CNAME
    - README.md
    - Vagrantfile
