name: Nate Woods
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
paginate: 20
paginate_path: "/blog/:num/"
permalink: /blog/:year/:month/:title.html
exclude:
    - node_modules
    - gruntfile.js
    - gulpfile.js
    - package.json
    - CNAME
    - README.md
    - develop
plugins: [jekyll-paginate]
kramdown:
    input: GFM
    syntax_highlighter: rouge
