name: Nate Woods
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
permalink: /blog/:year/:title.html
exclude:
    - Dockerfile
    - README.md
    - makefile
    - main.go
    - go.mod
    - ship.sh
collections:
    snippets:
        output: true
        permalink: /snippets/:title.html
# defaults:
#     - scope:
#         path: ""
#         type: "snippets"
#       values:
#         layout: "post"