name: Nate Woods
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
permalink: /blog/:year/:title.html
exclude:
    - Dockerfile
    - README.md
    - makefile
    - main.go
    - go.mod
    - ship.sh
    - about.service
